export const GET_INGREDIENTS = " GET_INGREDIENTS";
export const ADD_INGREDIENT = " ADD_INGREDIENT";
export const ADD_TO_SHOPLIST = " ADD_TO_SHOPLIST";

export const GET_RECIPES = " GET_RECIPES";
export const SELECTED_RECIPE = " SELECTED_RECIPE";
